# Generated by Django 3.1.7 on 2021-03-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField(verbose_name='введите вопрос ответа')),
                ('first_var', models.TextField(verbose_name='введите первый вариант ответа')),
                ('second_var', models.TextField(verbose_name='введите второй вариант ответа')),
                ('third_var', models.TextField(verbose_name='введите третий вариант ответа')),
                ('fourth_var', models.TextField(verbose_name='введите четвёртый вариант ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=200, verbose_name='название теста')),
                ('test_text', models.IntegerField(verbose_name='количество вопросов')),
            ],
        ),
    ]
